[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
remappings = ["@ensdomains/=node_modules/@ensdomains/", "@openzeppelin/=node_modules/@openzeppelin/"]

[fuzz]
runs = 256

[fmt]
single_line_statement_blocks = "multi"
