import fs from "node:fs";
import path from "node:path";
import { test, expect } from "@playwright/test";
import { formatUnits } from "viem";
import { ART, PREVIEW, CREATOR, BUYER, OBS_START, SETTLE_TIME, CLAIM_END, UNIT } from "./constants";
import { client, deployment, marketAbi, oracleAbi, rentBalance, cashBalance, balance, lpBalance, warp, openWallet, syncClock, connectWallet, dismissToasts } from "./support";
import { setAccount } from "../support/helpers";
import { RAW, presentation, say, focus, click, fill, hold, publishCapture, type Chapter } from "./record.helpers";

test("record the complete backed RENT lifecycle with captions", async ({ browser }) => {
  test.setTimeout(600000);
  fs.mkdirSync(RAW, { recursive: true });
  const context = await browser.newContext({ baseURL: PREVIEW, viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1, recordVideo: { dir: RAW, size: { width: 1440, height: 1000 } } });
  const page = await context.newPage();
  const video = page.video()!;
  const began = Date.now();
  const chapters: Chapter[] = [];
  const proof: Record<string, unknown> = { scope: "Local Anvil chain 31337; synthetic USDC; test-key signed emails. No mainnet settlement or user funds.", chainId: 31337, deployment: deployment() };
  const d = deployment();
  const chapter = async (id: string, title: string, caption: string) => {
    console.log(`Recording chapter: ${title}`);
    chapters.push({ id, title, caption, start: Math.max(0, (Date.now() - began) / 1000) });
    await say(page, caption);
  };
  const go = async (route: string) => {
    await page.evaluate(route => { window.location.hash = route; }, route);
    await page.waitForTimeout(750);
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
    await hold(page, 1);
  };
  try {
    await openWallet(page, 0);
    await presentation(page);
    await page.goto("/#/");
    await connectWallet(page);
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible();
    await chapter("market", "The market and the three parties", "Rent risk, expressed as a fully backed token. One RENT can pay up to one USDC.");
    await hold(page, 10);
    const roles = page.getByRole("heading", { name: /three parties|three roles/i }).first();
    if (await roles.count()) await focus(page, roles);
    await say(page, "Platform: terms and oracle. Insurer: capital and pool liquidity. Renter: buys RENT and receives its payout.");
    await hold(page, 12);
    await focus(page, page.getByRole("heading", { name: "The market right now", exact: true }));
    await say(page, "The local example starts at $92.88/SF. Payouts span +3% to +8%; the next steps supply the backing.");
    await hold(page, 10);

    await go("/insurer");
    await chapter("insurer", "Price and fund the insurer position", "$100,000 modeled capital, 10% sold at $0.285: $2,850 premium and a known maximum net loss.");
    await fill(page, page.getByTestId("insurer-capital"), "100000");
    await fill(page, page.getByTestId("insurer-price"), "0.285");
    await fill(page, page.getByTestId("insurer-sold"), "10");
    await focus(page, page.getByTestId("insurer-sold"));
    await hold(page, 8);
    await fill(page, page.getByTestId("insurer-sold"), "50");
    await say(page, "At 50% sold, premium and claim exposure both rise. The calculator makes the trade-off visible before funding.");
    await hold(page, 8);
    await fill(page, page.getByTestId("insurer-sold"), "10");
    await fill(page, page.getByLabel("Collateral (USDC)", { exact: true }), "50000");
    await say(page, "Fund the actual local contract: 50,000 synthetic USDC goes into escrow and mints 50,000 RENT.");
    await hold(page, 5);
    await click(page, page.getByRole("button", { name: "Deposit and mint RENT", exact: true }));
    await expect.poll(() => rentBalance(CREATOR)).toBe(50000n * UNIT);
    expect(await balance(d.currency, d.market)).toBe(50000n * UNIT);
    await hold(page, 5); await dismissToasts(page);
    await fill(page, page.getByLabel("RENT to add", { exact: true }), "45000");
    await expect(page.getByTestId("liquidity-usdc-required")).toContainText("12,825");
    await say(page, "Seed Uniswap separately with RENT and USDC. Trading uses pool inventory; the 50,000 USDC backing stays in escrow.");
    await hold(page, 6);
    await click(page, page.getByRole("button", { name: "Add liquidity", exact: true }));
    await expect.poll(lpBalance).toBeGreaterThan(0n);
    expect(await balance(d.currency, d.market)).toBe(50000n * UNIT);
    proof.initialBacking = "50000 USDC"; proof.liquidity = (await lpBalance()).toString();
    await hold(page, 6); await dismissToasts(page);

    await setAccount(page, 1); await go("/renter");
    await chapter("renter", "Size the renter cover and explore outcomes", "$60,000 annual rent implies 3,000 RENT for the five-point band. At a modeled $0.285, the cost is $855.");
    await fill(page, page.getByTestId("renter-rent"), "60000");
    await fill(page, page.getByTestId("renter-price"), "0.285");
    await hold(page, 9);
    await click(page, page.getByRole("button", { name: "+3%", exact: true }));
    await expect(page.getByTestId("renter-outcome-payout")).toContainText("$0");
    await say(page, "At +3% index growth: zero payout. The token only covers growth above the lower strike.");
    await hold(page, 5);
    await click(page, page.getByRole("button", { name: "+5%", exact: true }));
    await expect(page.getByTestId("renter-outcome-payout")).toContainText("$1,200");
    await say(page, "At +5% index growth: 3,000 RENT pays $1,200. The payout rises linearly through the band.");
    await hold(page, 5);
    await click(page, page.getByRole("button", { name: "+8%", exact: true }));
    await expect(page.getByTestId("renter-outcome-payout")).toContainText("$3,000");
    await say(page, "At +8% or more: the maximum is $3,000. The payout follows the published rent index.");
    await hold(page, 6);

    await click(page, page.getByTestId("renter-buy"));
    await expect(page.getByTestId("rent-current-price")).toContainText("Trading open");
    await expect(page.getByText("We filled in its current cost below", { exact: false })).toBeVisible();
    await chapter("trade", "Buy and sell through the live local v4 pool", "Checkout separates spot price, simple conversion and executable pool quote. Buying 3,000 RENT moves the price.");
    await focus(page, page.getByTestId("spot-conversion"));
    await hold(page, 10);
    const spend = await page.getByLabel("You pay (USDC)", { exact: true }).inputValue();
    const cashBefore = await cashBalance(BUYER);
    await click(page, page.getByRole("button", { name: "Confirm trade", exact: true }));
    await expect.poll(() => rentBalance(BUYER)).toBeGreaterThan(2999n * UNIT);
    const bought = await rentBalance(BUYER);
    proof.purchase = { spendUSDC: spend, receivedRENT: formatUnits(bought, 6), cashSpent: formatUnits(cashBefore - await cashBalance(BUYER), 6) };
    await say(page, `Confirmed: ${Number(formatUnits(bought, 6)).toLocaleString("en-US", { maximumFractionDigits: 3 })} RENT is now in the renter wallet. The actual quote includes pool impact and fees.`);
    await hold(page, 8); await dismissToasts(page);
    await click(page, page.getByRole("button", { name: "Sell", exact: true }));
    await fill(page, page.getByLabel("You pay (RENT)", { exact: true }), "100");
    await say(page, "The same Buy & Sell screen also exits a position. Here, sell 100 RENT back to the pool before the observation window.");
    await hold(page, 6);
    await click(page, page.getByRole("button", { name: "Confirm trade", exact: true }));
    await expect.poll(() => rentBalance(BUYER)).toBe(bought - 100n * UNIT);
    proof.remainingRENT = formatUnits(await rentBalance(BUYER), 6);
    await hold(page, 5); await dismissToasts(page);

    await go("/market-view");
    await chapter("forecast", "Read the market price", "Price maps to a payout-equivalent growth level and index print. It is a priced capped payoff, not expected rent growth.");
    await hold(page, 10);
    await focus(page, page.getByTestId("v4-price-history-chart"));
    await expect(page.getByTestId("v4-swap-point")).toHaveCount(2);
    await say(page, "Both executed swaps appear in on-chain price history. Every trade can change the price and its implied level.");
    await hold(page, 9);

    await chapter("oracle", "Authenticate the email and fix the payout", "Advance the LOCAL chain into September 2027. This future newsletter is signed by the test key, not the real publisher.");
    await hold(page, 6);
    await warp(OBS_START); await syncClock(page);
    expect(await client.readContract({ address: d.market, abi: marketAbi, functionName: "tradingOpen" })).toBe(false);
    await go("/buy");
    await say(page, "The observation window closes trading. The hook enforces the timing on-chain.");
    await hold(page, 6);
    await warp(SETTLE_TIME + 60n); await syncClock(page); await go("/settle");
    await say(page, "Upload the original test-signed .eml. Browser preflight checks the body hash, RSA signature and parsed print.");
    await page.getByLabel("Original email (.eml)", { exact: true }).setInputFiles(path.join(ART, "settlement-test-only.eml"));
    await expect(page.getByTestId("v4-preflight")).toContainText("RSA signature");
    await expect(page.getByTestId("v4-preflight")).not.toContainText("✕");
    const parsed = page.getByTestId("signed-rent-summary");
    await focus(page, await parsed.count() ? parsed : page.getByTestId("v4-preflight"));
    await hold(page, 10);
    await click(page, page.getByRole("button", { name: "Authenticate email on-chain", exact: true }));
    await expect.poll(() => client.readContract({ address: d.oracle, abi: oracleAbi, functionName: "observationCount" })).toBe(2n);
    await say(page, "The on-chain verifier accepts the signed $97.99/SF print. It sits halfway between $95.67 and $100.31.");
    await hold(page, 8);
    await click(page, page.getByRole("button", { name: "Settle market", exact: true }));
    await expect.poll(() => client.readContract({ address: d.market, abi: marketAbi, functionName: "settled" })).toBe(true);
    expect(await client.readContract({ address: d.market, abi: marketAbi, functionName: "payoutRatioWad" })).toBe(500_000_000_000_000_000n);
    await say(page, "Settlement fixes the result permanently: each RENT redeems for 0.50 USDC in this local lifecycle.");
    await hold(page, 8); await dismissToasts(page);
    proof.settlement = { print: "$97.99/SF", ratio: "50%", testKeySigned: true };

    await go("/redeem");
    await chapter("redeem", "Burn RENT and receive escrowed USDC", "Redeem RENT burns the tokens and sends their fixed payout from the backing escrow, independently of Uniswap liquidity.");
    const renterRent = await rentBalance(BUYER), renterCash = await cashBalance(BUYER);
    await fill(page, page.getByLabel("RENT to redeem", { exact: true }), formatUnits(renterRent, 6));
    await hold(page, 7);
    await click(page, page.getByRole("button", { name: "Redeem RENT", exact: true }));
    await expect.poll(() => rentBalance(BUYER)).toBe(0n);
    expect(await cashBalance(BUYER)).toBe(renterCash + renterRent / 2n);
    await say(page, `Confirmed: ${Number(formatUnits(renterRent / 2n, 6)).toLocaleString("en-US", { maximumFractionDigits: 3 })} USDC paid from escrow. The redeemed RENT balance is now zero.`);
    await hold(page, 9); await dismissToasts(page);
    proof.renterPayoutUSDC = formatUnits(renterRent / 2n, 6);

    await setAccount(page, 0); await go("/insurer");
    await chapter("close", "Close the insurer lifecycle", "After settlement, the insurer removes its pool inventory and redeems any RENT it still owns.");
    await click(page, page.getByRole("button", { name: "Remove my liquidity", exact: true }));
    await expect.poll(lpBalance).toBe(0n);
    await hold(page, 5); await dismissToasts(page);
    const insurerRent = await rentBalance(CREATOR);
    await go("/redeem");
    await fill(page, page.getByLabel("RENT to redeem", { exact: true }), formatUnits(insurerRent, 6));
    await click(page, page.getByRole("button", { name: "Redeem RENT", exact: true }));
    await expect.poll(() => rentBalance(CREATOR)).toBe(0n);
    await say(page, "Advance the local chain past the claim deadline. Only then can the original funder withdraw the remaining backing.");
    await hold(page, 6);
    await warp(CLAIM_END + 1n); await syncClock(page); await go("/insurer");
    const residual = await balance(d.currency, d.market);
    await click(page, page.getByRole("button", { name: /^Withdraw [\d,.]+ USDC$/ }));
    await expect.poll(() => balance(d.currency, d.market)).toBe(0n);
    proof.residualUSDC = formatUnits(residual, 6); proof.finalEscrowUSDC = "0";
    proof.transactionHashes = [...new Set((await client.getLogs({ address: [d.market, d.poolManager, d.oracle], fromBlock: 0n, toBlock: "latest" })).map(log => log.transactionHash))];
    await say(page, "Lifecycle complete: funding, trading, signed-email settlement, token redemption and residual withdrawal—all verified on local contracts.");
    await hold(page, 9); await dismissToasts(page);
    await context.close();
    const raw = path.join(RAW, "rentsafe-lifecycle.webm");
    await video.saveAs(raw);
    fs.writeFileSync(path.join(ART, "recording-proof.json"), JSON.stringify(proof, null, 2));
    if (!process.env.RECORD_DRAFT) {
      const result = publishCapture(raw, "rentsafe-lifecycle", chapters, proof);
      console.log(`Published ${result.duration.toFixed(1)} seconds with ${result.chapters.length} chapters`);
    }
  } finally { await context.close(); }
});
