#!/usr/bin/env python3
"""Generate src/gen/CredailyKey.sol from fixtures/credaily-2026-09-17/meta.json.

The deploy script (script/Deploy.s.sol) and the tests use the generated constant so a
deployment has zero file dependencies. Re-run this script whenever meta.json changes:

    python3 scripts/gen-key-constant.py

The modulus in meta.json is the DKIM RSA-2048 public key for
b37._domainkey.newyork.credaily.com (see fixtures/credaily-2026-09-17/EVIDENCE.md).
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
META = ROOT / "fixtures" / "credaily-2026-09-17" / "meta.json"
OUT = ROOT / "src" / "gen" / "CredailyKey.sol"

TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @title CredailyKey
/// @notice AUTO-GENERATED by scripts/gen-key-constant.py from
///         fixtures/credaily-2026-09-17/meta.json — DO NOT EDIT BY HAND.
/// @dev RSA-2048 DKIM public key (e = 65537) served by DNS at
///      `{selector}._domainkey.{domain}` (SendGrid CNAME), captured and verified
///      2026-09-17; evidence chain in fixtures/credaily-2026-09-17/EVIDENCE.md.
library CredailyKey {{
    /// @notice 256-byte big-endian RSA modulus.
    bytes internal constant MODULUS =
        hex"{modulus_hex}";

    /// @notice keccak256(MODULUS) — fingerprint pinned by the oracle.
    bytes32 internal constant MODULUS_HASH = {modulus_keccak};

    /// @notice DKIM d= domain the oracle accepts.
    string internal constant DOMAIN = "{domain}";

    /// @notice DKIM s= selector the oracle accepts.
    string internal constant SELECTOR = "{selector}";
}}
"""


def keccak(data: bytes) -> bytes:
    """keccak-256 (NOT sha3-256). Pure-python fallback via eth-hash if available,
    else a minimal implementation."""
    try:
        from Crypto.Hash import keccak as _k  # pycryptodome

        h = _k.new(digest_bits=256)
        h.update(data)
        return h.digest()
    except ImportError:
        pass
    try:
        import sha3  # pysha3

        return sha3.keccak_256(data).digest()
    except ImportError:
        pass
    return _keccak_fallback(data)


def _keccak_fallback(data: bytes) -> bytes:
    """Minimal Keccak-256 (original padding 0x01), no dependencies."""
    RC = [
        0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000,
        0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
        0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
        0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003,
        0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A,
        0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008,
    ]
    ROT = [
        [0, 36, 3, 41, 18],
        [1, 44, 10, 45, 2],
        [62, 6, 43, 15, 61],
        [28, 55, 25, 21, 56],
        [27, 20, 39, 8, 14],
    ]
    MASK = (1 << 64) - 1

    def rol(x, n):
        return ((x << n) | (x >> (64 - n))) & MASK

    rate = 136  # 1088 bits for 256-bit output
    # pad10*1 with domain byte 0x01 (Keccak, not SHA-3's 0x06)
    padded = bytearray(data)
    padlen = rate - (len(padded) % rate)
    padded += b"\x01" + b"\x00" * (padlen - 2) + b"\x80" if padlen >= 2 else b"\x81"

    S = [[0] * 5 for _ in range(5)]
    for off in range(0, len(padded), rate):
        block = padded[off : off + rate]
        for i in range(rate // 8):
            x, y = i % 5, i // 5
            S[x][y] ^= int.from_bytes(block[8 * i : 8 * i + 8], "little")
        for rnd in range(24):
            C = [S[x][0] ^ S[x][1] ^ S[x][2] ^ S[x][3] ^ S[x][4] for x in range(5)]
            D = [C[(x - 1) % 5] ^ rol(C[(x + 1) % 5], 1) for x in range(5)]
            for x in range(5):
                for y in range(5):
                    S[x][y] ^= D[x]
            B = [[0] * 5 for _ in range(5)]
            for x in range(5):
                for y in range(5):
                    B[y][(2 * x + 3 * y) % 5] = rol(S[x][y], ROT[x][y])
            for x in range(5):
                for y in range(5):
                    S[x][y] = B[x][y] ^ ((~B[(x + 1) % 5][y]) & B[(x + 2) % 5][y])
            S[0][0] ^= RC[rnd]
    out = b""
    for i in range(rate // 8):
        x, y = i % 5, i // 5
        out += S[x][y].to_bytes(8, "little")
        if len(out) >= 32:
            break
    return out[:32]


def main() -> None:
    meta = json.loads(META.read_text())
    modulus_hex = meta["modulus_hex"].removeprefix("0x")
    modulus = bytes.fromhex(modulus_hex)
    assert len(modulus) == 256, f"expected 2048-bit modulus, got {len(modulus)} bytes"
    assert meta["exponent"] == 65537, "oracle assumes e = 65537"
    fingerprint = keccak(modulus)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        TEMPLATE.format(
            modulus_hex=modulus_hex,
            modulus_keccak="0x" + fingerprint.hex(),
            domain=meta["d"],
            selector=meta["s"],
        )
    )
    print(f"wrote {OUT}")
    print(f"modulus keccak256: 0x{fingerprint.hex()}")


if __name__ == "__main__":
    main()
