#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../", import.meta.url));
const names = ["RentV4Market", "RentV4Factory", "RentV4Hook", "RentV4Router", "ChunkedObservationSubmitter"];
let output = '// Generated by scripts/gen-v4-abi.mjs from compiled Solidity.\nimport type { Abi } from "viem";\n';
for (const name of names) {
  const abi = JSON.parse(execFileSync("forge", ["inspect", name, "abi", "--json"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }));
  output += `export const ${name}Abi = ${JSON.stringify(abi)} as const satisfies Abi;\n`;
}
writeFileSync(new URL("../web/src/chain/v4Abi.ts", import.meta.url), output);
